### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
Fix permissions

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM I guess

Not sure why the tests are failing with

>4447 WARNING chmod: cannot access '/var/www/invidious/bin': No such file or directory

during backup restore o.O

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
