### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem
#3

## Solution
- *Add `Add more_set_headers` to NGINX conf*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/invidious_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@georgelemental Thank you for the feedback. Can you try this and see if it works?

**Comment by georgelemental** [comment]
@ericgaspar No, while it does add the proper header it also makes all `/embed/` links give a 404.

**Comment by ericgaspar** [comment]
!testme

**Comment by georgelemental** [comment]
> @ericgaspar No, while it does add the proper header it also makes all `/embed/` links give a 404.

This was never fixed. Now that his MR has been merged the bug is in production.

**Pull request merged**
